import {escape as e,icon,avatar} from './ui.js';
import {gameLogo,character,windowBar,medal} from './game-art.js';
const button=(label,action,cls='secondary')=>`<button class="btn ${cls}" data-action="${action}">${label}</button>`;
const panel=(name,body,color='blue')=>`<section class="game-window">${windowBar(name,color)}<div class="window-content">${body}</div></section>`;
const avatars=selected=>`<fieldset class="avatar-field"><legend>Escolha seu personagem</legend><div class="avatar-options">${['explorer','android'].map((id,i)=>`<label class="avatar-choice"><input type="radio" name="avatar" value="${id}" ${id===selected?'checked':''}>${character(id)}<span>${i?'Android':'Explorador'}</span></label>`).join('')}</div></fieldset>`;
const emailField=(value='')=>`<label for="email">E-mail</label><input id="email" type="email" name="email" value="${e(value)}" required autocomplete="email" maxlength="254">`;
const email=emailField();
const password=(newPassword=false)=>`<label for="password">${newPassword?'Nova senha':'Senha'}</label><input id="password" type="password" name="password" required minlength="${newPassword?8:1}" autocomplete="${newPassword?'new-password':'current-password'}">`;
const scene=(body,notice)=>`<section class="profile-scene auth-scene"><div class="profile-brand">${gameLogo()}</div><div class="profile-interface auth-interface"><div id="auth-feedback" class="auth-feedback" data-kind="${notice?.type==='error'?'error':'success'}" role="${notice?.type==='error'?'alert':'status'}" ${notice?'':'hidden'}>${e(notice?.message||'')}</div>${body}</div></section>`;
export function createAccountScreens({profile:p,rankingData,confirmationEmail='',authNotice}) {
  const accountScene=body=>scene(body,authNotice);
  return {
    profiles:()=>accountScene(panel('ENTRAR NA AVENTURA',`<h1 tabindex="-1">Seu explorador espera por você.</h1><form id="login-form">${email}${password()}<button class="btn primary" type="submit">ENTRAR ${icon('arrow')}</button></form><div class="auth-links">${button('CRIAR CONTA','signup')}${button('Esqueci minha senha','reset','text')}</div><p class="field-help">Sua aventura acompanha sua conta em outros dispositivos.</p>`)),
    signup:()=>accountScene(panel('NOVO EXPLORADOR',`<h1 tabindex="-1">Comece sua história.</h1><form id="signup-form"><label for="nickname">Apelido no jogo</label><input id="nickname" name="nickname" required minlength="2" maxlength="24" autocomplete="nickname">${email}${password(true)}${avatars('explorer')}<button class="btn primary" type="submit">CRIAR CONTA ${icon('play')}</button></form><p class="field-help">Confirme o e-mail para entrar. Você começa com 100 CodeCoins.</p>${button('Já tenho uma conta','profiles','text')}`)),
    confirmation:()=>accountScene(panel('CONFIRMAR E-MAIL',`<h1 tabindex="-1">Falta um passo para começar.</h1><p>Abra o link de confirmação recebido por e-mail. Confira também a pasta de spam e se o endereço está correto.</p><form id="resend-form">${emailField(confirmationEmail)}<button class="btn primary" type="submit">REENVIAR CONFIRMAÇÃO ${icon('arrow')}</button></form><p class="field-help">O envio pode demorar alguns minutos. Aguarde antes de pedir novamente.</p>${button('JÁ CONFIRMEI · ENTRAR','profiles','secondary')}${button('Corrigir meu cadastro','signup','text')}`)),
    reset:()=>accountScene(panel('RECUPERAR ACESSO',`<h1 tabindex="-1">Vamos retomar sua aventura.</h1><p>Enviaremos um link para definir uma nova senha.</p><form id="reset-form">${email}<button class="btn primary" type="submit">ENVIAR LINK ${icon('arrow')}</button></form>${button('Voltar para entrar','profiles','text')}`)),
    password:()=>accountScene(panel('NOVA SENHA',`<h1 tabindex="-1">Proteja sua aventura.</h1><form id="password-form">${password(true)}<label for="confirmation">Confirme a nova senha</label><input id="confirmation" name="confirmation" type="password" autocomplete="new-password" required minlength="8" maxlength="128"><button class="btn primary" type="submit">SALVAR NOVA SENHA ${icon('check')}</button></form>${button('Sair','logout','text')}`)),
    settings:()=>`<section class="options-scene"><div class="screen-title"><h1 tabindex="-1">Opções</h1><p>Seu personagem. Sua experiência.</p></div><div class="two-col">${panel('PERSONAGEM',`<form id="rename-form"><label for="rename">Apelido</label><input id="rename" name="nickname" value="${e(p.apelido)}" minlength="2" maxlength="24" required>${avatars(p.avatarId)}<button class="btn primary" type="submit">SALVAR PERSONAGEM ${icon('check')}</button></form>`)}${panel('EXPERIÊNCIA',`<label class="setting-row"><span>${icon('sound')} Som do jogo</span><input type="checkbox" id="sound-setting" ${p.settings.sound?'checked':''}></label><label class="setting-row"><span>Música de aventura</span><input type="checkbox" id="music-setting" ${p.settings.music?'checked':''}></label><label class="setting-row volume-setting"><span>Volume</span><input type="range" id="volume-setting" min="0" max="100" step="5" value="${p.settings.volume}" aria-label="Volume do jogo"><output for="volume-setting">${p.settings.volume}%</output></label><label class="setting-row"><span>Animações</span><input type="checkbox" id="motion-setting" ${p.settings.motion?'checked':''}></label><hr><h2>Sua conta</h2><p>Partidas, conquistas e progresso ficam salvos na sua conta.</p>${button('RECUPERAR SENHA','reset')}${button(icon('logout')+' SAIR DO PERFIL','logout','text')}`,'teal')}</div></section>`,
    ranking:()=>{
      const players=rankingData?.players||[],mine=rankingData?.mine;
      return `<section class="ranking-scene"><div class="ranking-medals"><div class="small-medals">${medal('bronze')}${medal('silver')}${medal('gold')}</div><div class="ranking-your-medal">${medal(mine?.position===1?'gold':mine?.position===2?'silver':'bronze')}<strong>${mine?mine.position+'º LUGAR':'SEM POSIÇÃO'}</strong><span>SUA POSIÇÃO NA CAMPANHA</span></div></div>${panel('CLASSIFICAÇÃO',`<div class="screen-title"><h1 tabindex="-1">Ranking da campanha</h1><p>Os recordes de todos os exploradores.</p></div><div class="ranking-list">${players.map(player=>`<div class="ranking-row ${player.you?'you':''}"><span class="rank-position">${player.position}º</span>${avatar(player.avatarId)}<span class="ranking-name"><strong>${e(player.apelido)}</strong><small>${player.you?'VOCÊ':''}</small></span><span class="ranking-stars">${icon('star')}${player.stars}</span><strong>${player.score.toLocaleString('pt-BR')}<small>PTS</small></strong></div>`).join('')||'<p>A campanha está começando. Jogue a primeira fase!</p>'}</div><p class="field-help">Soma dos melhores resultados de cada fase. Desempate por estrelas e apelido. Mostrando até 100 jogadores.</p>`,'violet')}</section>`;
    }
  };
}
