// Banco autoral. Cada registro: enunciado, correta, distratores, explicação, código opcional.
// IDs são derivados da posição: preserve posições ao revisar a mesma habilidade.
import { writeFile } from 'node:fs/promises';
const banks = {
fundamentos: [
['O que é programar?','Escrever instruções para um computador','Trocar peças do computador|Desenhar apenas ícones|Conectar um cabo à internet','Programar é expressar instruções que o computador pode executar.'],
['O que é um programa?','Um conjunto de instruções','Um monitor|Uma bateria|Um cabo de rede','Um programa organiza instruções para realizar tarefas.'],
['Para que serve uma linguagem de programação?','Expressar instruções com regras definidas','Aumentar a memória física|Substituir o processador|Produzir energia','Uma linguagem fornece sintaxe e significado para escrever programas.'],
['O que é código-fonte?','O texto das instruções escritas pelo programador','Somente o resultado na tela|Um arquivo de imagem obrigatório|O nome do computador','Código-fonte é a representação textual do programa.'],
['O que significa executar um programa?','Realizar suas instruções','Apagar seu código|Mudar o monitor|Escrever uma senha','Executar significa realizar as operações descritas pelo programa.'],
['Qual é o papel de um comentário no código?','Explicar o código para quem o lê','Somar automaticamente números|Criar uma saída obrigatória|Executar uma instrução secreta','Comentários documentam o código e não são executados como instruções.'],
['Qual símbolo inicia um comentário de uma linha em JavaScript?','//','##|<!--|**','Em JavaScript, // comenta o restante da linha.'],
['O que é sintaxe?','As regras de escrita de uma linguagem','O resultado de uma soma|A velocidade da internet|Um tipo de monitor','A sintaxe determina as formas válidas de escrever instruções.'],
['O que é um erro de lógica?','Uma instrução válida que resolve o problema incorretamente','Uma tela desligada|Um programa sempre correto|Um comentário longo','O programa pode executar sem erro de sintaxe e ainda produzir um resultado incorreto.'],
['O que é depuração?','Investigar e corrigir erros do programa','Excluir todos os arquivos sempre|Aumentar o brilho|Trocar o nome da linguagem','Depurar é localizar a causa de um erro e corrigi-la.'],
['Qual prática ajuda a compreender um código?','Usar nomes claros e organizar as instruções','Remover todos os espaços e nomes|Esconder toda a saída|Usar apenas uma letra em todo nome','Legibilidade facilita revisão, manutenção e colaboração.'],
['Qual item é uma linguagem de programação?','JavaScript','Teclado|Monitor|Impressora','JavaScript é uma linguagem; os demais itens são dispositivos.'],
['O que um teste de software verifica?','Se o comportamento atende a um resultado esperado','Se o computador tem uma cor específica|Se todo código é infalível|Se nenhuma revisão será necessária','Testes comparam resultados observados com resultados esperados.'],
['Por que definir o problema antes de escrever código?','Para saber qual resultado o programa deve produzir','Para eliminar a necessidade de instruções|Para escolher apenas cores|Para evitar qualquer teste','Uma definição clara orienta as entradas, o processamento e as saídas.'],
['Qual prática é adequada ao aprender programação?','Testar, observar resultados e revisar a solução','Memorizar letras de respostas apenas|Ignorar mensagens de erro|Copiar sem compreender','Testar e analisar erros ajuda a construir compreensão.'],
['O que o trecho exibe?','Olá','Nada|console.log|Um erro de variável','console.log exibe o texto fornecido entre aspas.','console.log("Olá");'],
['Qual linha é ignorada durante a execução?','// Exibir saudação','console.log("Olá");|console.log(2);|console.log(3);','A linha iniciada por // é um comentário.','// Exibir saudação\nconsole.log("Olá");'],
['Qual é a ordem das saídas?','Início, Fim','Fim, Início|Somente Fim|Somente Início','As instruções de saída são executadas de cima para baixo.','console.log("Início");\nconsole.log("Fim");'],
['Qual linha exibe um número?','console.log(7);','// console.log(7);|"console.log(7)";|let numero = 7;','Só a chamada não comentada de console.log imprime o número.'],
['Qual problema existe no trecho?','A string não foi fechada com aspas','O texto tem poucas letras|console.log não aceita texto|Falta um comentário','A aspa de abertura precisa de uma aspa de fechamento.','console.log("Olá);'],
['Qual comentário de bloco é válido em JavaScript?','/* descrição */','<!-- descrição -->|## descrição ##|** descrição **','Comentários de bloco usam /* para abrir e */ para fechar.'],
['O que acontece com a linha comentada?','Não produz saída','Exibe 9|Interrompe sempre o programa|Exibe as barras','Um comentário não é executado.','// console.log(9);'],
['Uma calculadora subtrai quando deveria somar. Que erro isso sugere?','Erro de lógica','Obrigatoriamente erro de aspas|Falha de monitor|Ausência de fonte de energia','Uma operação válida pode estar errada para a tarefa desejada.'],
['Qual alteração deixa a intenção mais clara?','Trocar x por precoTotal','Trocar x por z|Remover todos os comentários|Usar espaços no nome da variável','precoTotal descreve melhor o significado do valor.','let x = 80;'],
['O programa deveria exibir 12. Qual linha causa a divergência?','A linha que subtrai b de a','A criação de a|A criação de b|A chamada de console.log','Para obter a soma de 8 e 4, a operação precisa ser a + b.','let a = 8;\nlet b = 4;\nlet total = a - b;\nconsole.log(total);'],
['Qual é a sequência de saídas, considerando o comentário?','A, C','A, B, C|B, C|Somente C','A chamada que exibiria B está dentro de um comentário de bloco.','console.log("A");\n/* console.log("B"); */\nconsole.log("C");'],
['Qual teste revela melhor o erro da função de cálculo descrita?','Usar 2 e 3 e esperar 5','Usar 0 e 0 e esperar 0|Usar apenas números iguais|Verificar só o nome do arquivo','O cálculo errado a - b passa para 0 e 0. Entradas diferentes revelam a divergência em relação à soma.','// A tarefa é somar a e b.\n// A implementação usa a - b.'],
['Qual correção resolve o erro sem mudar a intenção de exibir texto?','Fechar a string antes do parêntese','Remover console.log|Transformar toda a linha em comentário|Excluir somente o parêntese final','A chamada correta é console.log("Pronto");.','console.log("Pronto);'],
['Por que um único teste aprovado não garante ausência de erros?','Outras entradas podem seguir comportamentos não testados','Testes nunca executam código|Um teste sempre cobre todas as entradas|Resultados esperados não importam','Cada teste cobre um cenário. Outros cenários podem revelar defeitos.'],
['Qual estratégia ajuda a encontrar onde um resultado se torna incorreto?','Inspecionar valores intermediários do cálculo','Mudar todos os nomes de uma vez|Apagar todo o código antes de observar|Ignorar a saída final','Valores intermediários permitem identificar a primeira divergência em relação ao resultado esperado.']
],
algoritmos: [
['O que é um algoritmo?','Uma sequência de passos para resolver um problema','Um dispositivo físico|Uma linguagem obrigatória|Uma imagem','Um algoritmo descreve um procedimento organizado.'],
['Qual sequência faz sentido para preparar um chá?','Aquecer água, colocar no chá, servir','Servir, aquecer água, colocar no chá|Beber, servir, aquecer água|Servir sem preparar','A ordem precisa respeitar as dependências entre os passos.'],
['Qual é a primeira etapa ao resolver um problema?','Compreender o objetivo e os dados disponíveis','Escolher uma resposta aleatória|Apagar o sistema|Escrever qualquer saída','Compreender o problema permite planejar uma solução adequada.'],
['O que é pseudocódigo?','Uma descrição estruturada de um algoritmo','Uma linguagem que todo navegador executa|Um tipo de teclado|Um banco de imagens','Pseudocódigo comunica a lógica sem exigir a sintaxe completa de uma linguagem.'],
['Qual característica favorece um bom algoritmo?','Passos claros e ordenados','Instruções ambíguas|Ausência de objetivo|Resultados sempre aleatórios','Cada passo precisa ser compreensível e contribuir para a tarefa.'],
['O que significa seguir uma sequência?','Executar passos na ordem estabelecida','Executar todos os passos ao mesmo tempo sempre|Ignorar qualquer entrada|Escolher só a última instrução','Uma sequência define uma ordem de execução.'],
['Em um cálculo de média, o que deve vir antes da divisão?','Somar os valores','Exibir a média final|Apagar os valores|Converter o resultado em imagem','A média aritmética divide a soma pela quantidade de valores.'],
['Uma receita pode representar um algoritmo?','Sim, porque descreve passos para atingir um resultado','Não, algoritmos só existem em computadores|Não, toda receita é uma variável|Sim, mas só se contiver JavaScript','Algoritmos também aparecem em procedimentos cotidianos.'],
['Por que a ordem das instruções importa?','Um passo pode depender do resultado de outro','Toda ordem sempre produz a mesma saída|Apenas muda a cor da tela|Só afeta os comentários','Dependências entre passos podem tornar algumas ordens inválidas.'],
['O que é um teste de mesa?','Simular os passos e acompanhar valores manualmente','Testar a resistência da mesa|Executar só a última linha|Converter texto em áudio','Um teste de mesa ajuda a verificar a lógica do algoritmo.'],
['O que representa o resultado de um algoritmo?','A saída produzida pelos passos','Sempre o código-fonte|Sempre uma senha|A marca do computador','A saída é o resultado observável do processamento.'],
['Qual instrução é mais precisa?','Some 2 ao valor de pontos','Faça algo com pontos|Melhore o resultado|Use algum número','Instruções específicas evitam interpretações diferentes.'],
['Para calcular o dobro de um número, qual passo é necessário?','Multiplicar o número por 2','Dividir o número por 2|Somar 1|Transformar em texto','O dobro corresponde a duas vezes o valor.'],
['Qual sequência é típica de um processamento de dados?','Entrada, processamento, saída','Saída, saída, entrada|Processamento antes de todos os dados necessários|Somente saída','O programa recebe dados, trabalha com eles e apresenta um resultado.'],
['O que significa decompor um problema?','Dividi-lo em tarefas menores','Excluir o objetivo|Evitar qualquer planejamento|Escolher uma linguagem aleatória','Tarefas menores facilitam a construção e a revisão da solução.'],
['Qual é o valor final de x?','6','2|4|8','x começa com 2, recebe mais 1 e depois é multiplicado por 2.','let x = 2;\nx = x + 1;\nx = x * 2;'],
['Qual ordem calcula o preço total de uma compra?','Ler preço e quantidade, multiplicar, exibir','Exibir, ler, multiplicar|Multiplicar antes de conhecer ambos os dados|Ler quantidade, exibir apenas preço','O produto precisa dos dois dados antes de ser calculado.'],
['Qual é a saída?','8','3|5|15','A soma é calculada antes da saída.','let a = 3;\nlet b = 5;\nlet soma = a + b;\nconsole.log(soma);'],
['Qual é o valor final de saldo?','13','10|7|16','A ordem aplica a retirada de 3 e depois o crédito de 6.','let saldo = 10;\nsaldo = saldo - 3;\nsaldo = saldo + 6;'],
['Qual etapa falta para obter a média?','Dividir a soma por 2','Multiplicar a soma por 2|Subtrair uma nota|Exibir apenas nota1','A média de duas notas é a soma dividida por 2.','let nota1 = 6;\nlet nota2 = 8;\nlet soma = nota1 + nota2;'],
['O que será exibido?','4','8|2|16','Primeiro 8 é dividido por 2; o valor resultante é exibido.','let n = 8;\nn = n / 2;\nconsole.log(n);'],
['Qual é o primeiro resultado exibido?','2','5|7|0','A primeira saída acontece antes de atualizar n.','let n = 2;\nconsole.log(n);\nn = 5;\nconsole.log(n);'],
['Qual instrução deve vir antes de console.log(total)?','Calcular total a partir de preco e quantidade','Apagar total|Trocar o monitor|Somente criar um comentário','O valor calculado precisa existir antes de ser usado.'],
['Ao somar 1 e depois multiplicar por 3 a partir de 4, qual é o resultado?','15','13|12|7','A sequência produz 5 e depois 15.'],
['Qual sequência de operações faz x terminar em 18?','Somar 3, depois multiplicar por 2','Multiplicar por 2, depois somar 3|Dividir por 2, depois somar 3|Subtrair 3, depois multiplicar por 2','Partindo de 6, (6 + 3) × 2 resulta em 18.','let x = 6;'],
['Por que o trecho não troca os valores originais de a e b?','O valor original de a é perdido na primeira atribuição','Variáveis nunca podem trocar valores|A soma acontece automaticamente|b mantém 9','Após a = b, ambos valem 9; b = a mantém esse mesmo valor. É preciso guardar um valor temporário.','let a = 4;\nlet b = 9;\na = b;\nb = a;'],
['Quais valores ficam em a e b?','a = 9 e b = 4','a = 4 e b = 9|a = 9 e b = 9|a = 4 e b = 4','temp preserva o valor original de a para concluir a troca.','let a = 4;\nlet b = 9;\nlet temp = a;\na = b;\nb = temp;'],
['Qual é o valor final de resultado?','10','6|14|8','O dobro de 4 é 8; somar 6 dá 14; subtrair 4 dá 10.','let base = 4;\nlet resultado = base * 2;\nresultado = resultado + 6;\nresultado = resultado - base;'],
['Qual alteração faz o algoritmo usar o preço com desconto?','Calcular total depois de atualizar preco','Exibir total duas vezes|Mudar quantidade para texto|Adicionar um comentário no fim','total guarda o cálculo já feito. Atualizar preco depois não recalcula total automaticamente.','let preco = 10;\nlet quantidade = 2;\nlet total = preco * quantidade;\npreco = 8;\nconsole.log(total);'],
['Quais são as duas saídas?','6 e 10','6 e 6|10 e 10|3 e 5','A primeira saída usa n = 3. Depois n passa a 5 e o dobro passa a 10.','let n = 3;\nconsole.log(n * 2);\nn = n + 2;\nconsole.log(n * 2);']
],
entrada_saida: [
['O que é uma entrada de dados?','Uma informação recebida pelo programa','Somente um resultado impresso|Um comentário|Um erro obrigatório','Entrada é um dado recebido para ser utilizado no processamento.'],
['O que é uma saída de dados?','Um resultado apresentado pelo programa','Uma tecla antes de ser lida|Uma variável nunca usada|Um cabo elétrico','Saída comunica o resultado ao usuário ou a outro sistema.'],
['Qual é um exemplo de entrada?','O nome digitado em um formulário','A média exibida após o cálculo|Uma mensagem de resultado|Um relatório gerado','O texto digitado é fornecido ao programa.'],
['Qual é um exemplo de saída?','O total exibido na tela','A nota digitada pelo estudante|O preço recebido de um formulário|A idade informada pelo usuário','O total apresentado é um resultado do programa.'],
['Para que serve console.log?','Exibir uma informação no console','Ler sempre uma senha|Criar uma página automaticamente|Apagar variáveis','console.log é usado para apresentar valores no console.'],
['Em um navegador, o que prompt normalmente retorna após confirmação?','Uma string','Sempre um número|Sempre um booleano|Um programa completo','prompt retorna o texto informado, como string; ao cancelar, retorna null.'],
['Qual operação é processamento?','Calcular o total de uma compra','Digitar o preço|Ler o resultado na tela|Clicar para informar a quantidade','O processamento transforma dados de entrada em resultados.'],
['O que é validar uma entrada?','Verificar se o dado atende às condições esperadas','Aceitar todo texto como correto|Exibir o dado sem analisar|Apagar todos os valores','A validação verifica, por exemplo, formato, limites e obrigatoriedade.'],
['Uma mensagem de erro pode ser uma saída?','Sim, ela comunica um resultado ao usuário','Não, saídas são sempre números|Não, saídas são apenas imagens|Sim, mas só em arquivos impressos','Saídas também incluem mensagens sobre problemas.'],
['Qual dispositivo costuma fornecer entrada?','Teclado','Monitor exibindo um resultado|Caixa de som reproduzindo áudio|Impressora imprimindo um relatório','O teclado permite enviar dados ao sistema.'],
['Qual dispositivo costuma apresentar saída?','Monitor','Teclado digitando texto|Mouse ao clicar|Microfone captando voz','O monitor apresenta informações visuais ao usuário.'],
['Por que informar claramente o dado solicitado?','Para o usuário saber o que deve fornecer','Para impedir todo processamento|Para obrigar a usar números negativos|Para eliminar a saída','Uma solicitação clara reduz entradas inadequadas.'],
['Qual dado é necessário para calcular o dobro da idade?','A idade','A cor da tela|O nome do navegador|O número de comentários','O cálculo depende do valor numérico da idade.'],
['O que acontece ao exibir uma variável com console.log?','O valor atual é apresentado','Ela é apagada|Ela é sempre convertida em zero|O programa deixa de existir','A saída não apaga nem altera automaticamente a variável.'],
['Qual exemplo contém entrada, processamento e saída?','Receber duas notas, calcular a média e exibi-la','Exibir uma imagem sem receber dados novos|Digitar um nome sem utilizá-lo|Criar um comentário','As notas entram, a média é calculada e o resultado é apresentado.'],
['Qual é a saída?','Ana','nome|undefined|Nenhuma','console.log(nome) usa o valor armazenado, não o nome literal da variável.','let nome = "Ana";\nconsole.log(nome);'],
['Qual é a saída do trecho?','nome','Ana|null|Um erro de sintaxe','As aspas fazem nome ser um texto literal.','let nome = "Ana";\nconsole.log("nome");'],
['Se a entrada confirmada em prompt for 5, qual é o valor de entrada?','A string "5"','O número 5 obrigatoriamente|true|null','prompt retorna texto mesmo quando os caracteres representam um número.','let entrada = prompt("Número:");'],
['Qual é o resultado apresentado?','10','55|5|0','Number converte o texto 5 em número antes da multiplicação.','let entrada = "5";\nlet numero = Number(entrada);\nconsole.log(numero * 2);'],
['Qual saída comunica melhor o resultado ao usuário?','"Total: 30"','Somente uma tela vazia|"erro" para toda compra|Um comentário invisível','Uma mensagem contextualizada identifica o significado do valor.'],
['O que prompt retorna quando o usuário cancela?','null','0 obrigatoriamente|A string "cancelar"|true','O cancelamento é sinalizado por null e deve ser tratado pelo programa.'],
['Qual é a saída?','Olá, Lia','Olá, nome|LiaOlá,|0','O operador + concatena os dois textos.','let nome = "Lia";\nconsole.log("Olá, " + nome);'],
['Qual etapa é processamento neste trecho?','let total = preco * quantidade;','let preco = 12;|let quantidade = 3;|console.log(total);','A multiplicação transforma os dados em um resultado.','let preco = 12;\nlet quantidade = 3;\nlet total = preco * quantidade;\nconsole.log(total);'],
['Qual é a saída?','18','9|27|"99"','O valor numérico 9 é duplicado.','let valorRecebido = 9;\nconsole.log(valorRecebido + valorRecebido);'],
['Por que o trecho exibe 23 em vez de 5?','As duas entradas são strings e + concatena','console.log nunca soma|O operador + multiplica|O número 5 não pode ser exibido','Converta cada entrada para número antes de somar.','let a = "2";\nlet b = "3";\nconsole.log(a + b);'],
['Qual correção soma corretamente as duas entradas de texto?','Number(a) + Number(b)','Number(a + b)|a + b|String(a) + String(b)','Cada entrada deve ser convertida antes da soma; converter a concatenação daria 23.','let a = "2";\nlet b = "3";'],
['Qual valor é exibido após o cálculo?','7','6|8|14','As strings são convertidas para números; a soma 14 é dividida por 2.','let n1 = "6";\nlet n2 = "8";\nlet media = (Number(n1) + Number(n2)) / 2;\nconsole.log(media);'],
['Qual problema deve ser tratado antes de converter uma entrada cancelada?','Verificar se a entrada é null','Exibir sempre aprovação|Multiplicar por 100|Somar uma string vazia','Number(null) resulta em 0. É preciso distinguir cancelamento de um zero informado.','let entrada = prompt("Informe a nota:");'],
['Qual é a saída?','Total: 24','Total: 83|24Total:|Total: 11','Primeiro a multiplicação calcula 24; depois o texto é concatenado.','let preco = "8";\nlet quantidade = "3";\nconsole.log("Total: " + Number(preco) * Number(quantidade));'],
['Qual é a melhor validação conceitual para uma idade?','Verificar número finito e faixa aceitável antes de usar','Aceitar qualquer texto como idade|Verificar só se há uma letra|Converter e ignorar o resultado','A conversão pode falhar ou gerar valores fora do domínio esperado; ambos precisam ser verificados.']
],
variaveis: [
['O que é uma variável?','Um nome associado a um valor no programa','Um sistema operacional|Um cabo|Uma tela','Variáveis permitem armazenar e usar informações.'],
['Qual palavra permite declarar uma variável reatribuível?','let','const apenas|console|number','let cria uma variável que pode receber outro valor.'],
['Qual palavra declara uma ligação que não pode ser reatribuída?','const','let|log|prompt','const impede reatribuir a ligação a outro valor.'],
['O que o operador = faz em uma atribuição?','Atribui o valor da direita ao nome da esquerda','Compara obrigatoriamente dois valores|Multiplica valores|Exibe no console','Atribuição armazena um valor; comparação usa outros operadores.'],
['Qual nome é válido em JavaScript?','idadeAluno','2idade|idade-aluno|idade aluno','Um identificador não pode começar com um dígito nem conter espaço ou hífen.'],
['Qual declaração inicializa uma variável com 10?','let pontos = 10;','let 10 = pontos;|pontos let 10;|console = let 10;','A declaração combina let, nome e valor inicial.'],
['O que é inicializar uma variável?','Dar a ela um valor inicial','Apagar todo programa|Exibir sempre seu nome|Converter tudo para string','A inicialização estabelece o primeiro valor.'],
['Qual nome comunica melhor uma quantidade de moedas?','saldoMoedas','x|abc|coisa','Um nome descritivo facilita compreender o dado armazenado.'],
['JavaScript distingue idade de Idade?','Sim, são identificadores diferentes','Não, letras maiúsculas são ignoradas|Só em comentários|Só se houver números','JavaScript distingue maiúsculas e minúsculas em identificadores.'],
['Qual declaração armazena um texto?','let nome = "Lia";','let nome = Lia;|let "nome" = Lia;|nome let "Lia";','Aspas delimitam o valor de texto.'],
['Para uma referência que não será reatribuída, qual declaração usar?','const','console.log|prompt|return','const torna explícita a intenção de não reatribuir a ligação.'],
['Qual é o valor inicial de uma variável declarada com let sem atribuição?','undefined','0 sempre|Texto vazio sempre|false sempre','Sem inicialização, uma variável let contém undefined.'],
['Uma variável pode guardar um valor booleano?','Sim, como true ou false','Não, só números|Não, só textos|Sim, mas só entre aspas','Variáveis podem guardar valores de diferentes tipos.'],
['Qual é o valor de pontos após a atribuição?','25','0|pontos|undefined','O valor da direita é armazenado em pontos.','let pontos = 25;'],
['Qual símbolo pode fazer parte de um identificador JavaScript?','_','-|Um espaço|/','Sublinhado é permitido; hífen é interpretado como operador.'],
['Qual é a saída?','7','5|2|12','A segunda atribuição substitui o valor 5 por 7.','let x = 5;\nx = 7;\nconsole.log(x);'],
['Qual é o valor final de moedas?','80','100|20|120','A expressão lê o saldo anterior e subtrai 20.','let moedas = 100;\nmoedas = moedas - 20;'],
['Qual linha provoca erro de reatribuição?','limite = 20;','const limite = 10;|console.log(limite);|// limite máximo','Uma ligação const não aceita uma nova atribuição.','const limite = 10;\nlimite = 20;'],
['Qual é a saída?','3','1|2|0','Incrementar duas vezes transforma 1 em 3.','let n = 1;\nn = n + 1;\nn = n + 1;\nconsole.log(n);'],
['Qual é o valor de b?','4','9|13|undefined','b recebe uma cópia do valor numérico 4; reatribuir a não muda b.','let a = 4;\nlet b = a;\na = 9;'],
['Qual erro existe na saída?','O identificador Nome não foi declarado','Strings não podem ser exibidas|let não aceita textos|Falta um comentário','nome e Nome são identificadores diferentes.','let nome = "Rui";\nconsole.log(Nome);'],
['Qual expressão aumenta pontos em 10?','pontos = pontos + 10;','pontos = 10;|pontos - 10;|console.log(10);','A expressão usa o valor atual e armazena a soma na mesma variável.'],
['Qual é a saída?','undefined','0|1|Um texto vazio','A variável foi declarada sem valor inicial.','let resultado;\nconsole.log(resultado);'],
['Qual linha associa 2 ao nome quantidade?','let quantidade = 2;','let 2 = quantidade;|quantidade == 2;|console.log("quantidade");','A atribuição deve ter o identificador à esquerda.'],
['Quais são os valores finais de a e b?','a = 5 e b = 8','a = 8 e b = 8|a = 3 e b = 5|a = 5 e b = 5','a recebe 3 + 2 = 5; b usa esse novo a e recebe 5 + 3 = 8.','let a = 3;\nlet b = 2;\na = a + b;\nb = a + 3;'],
['Qual é o valor final de x?','12','4|8|16','y recebe o dobro do x original, 8. Depois x recebe 8 + 4.','let x = 4;\nconst y = x * 2;\nx = y + x;'],
['O que acontece neste trecho?','A propriedade nome muda para Bia','Toda propriedade const é imutável|A ligação pessoa é reatribuída|O objeto é apagado','const impede reatribuir a ligação; não congela automaticamente as propriedades do objeto.','const pessoa = { nome: "Ana" };\npessoa.nome = "Bia";'],
['Qual é a saída de b?','6','10|16|4','b preserva o valor 6 recebido antes da reatribuição de a.','let a = 6;\nlet b = a;\na = a + 4;\nconsole.log(b);'],
['Qual alteração corrige a intenção de atualizar o saldo?','Trocar const por let na declaração','Trocar 20 por "20"|Remover apenas o ponto e vírgula|Adicionar um comentário','O saldo será reatribuído; a declaração precisa permitir isso.','const saldo = 100;\nsaldo = saldo - 20;'],
['Qual é a sequência exibida?','2, 5, 2','2, 5, 5|5, 5, 5|2, 2, 2','O let do bloco cria outra variável n; a variável externa continua com 2.','let n = 2;\nconsole.log(n);\n{ let n = 5; console.log(n); }\nconsole.log(n);']
],
tipos: [
['Qual é o tipo de "Olá"?','string','number|boolean|undefined','Textos delimitados por aspas são strings.'],
['Qual é o tipo de 42?','number','string|boolean|null','42 é um literal numérico.'],
['Qual é o tipo de true?','boolean','string|number|undefined','Booleanos representam true ou false.'],
['Qual valor representa ausência intencional de valor?','null','"null"|1|"presente"','null é usado para representar ausência intencional; "null" é texto.'],
['Qual função converte uma string numérica para número?','Number','String|Boolean|console.log','Number realiza conversão para valor numérico.'],
['Qual função converte um valor para texto?','String','Number|Math.abs|console.log','String produz uma representação textual do valor.'],
['Qual operador informa o tipo de um valor?','typeof','+|=|%','typeof retorna uma string que descreve o tipo.'],
['Qual exemplo é um booleano, sem aspas?','false','"false"|0|"0"','false é booleano; "false" é uma string.'],
['Qual é a diferença entre 5 e "5"?','Um é número e o outro é texto','Ambos são sempre números|Ambos são booleanos|Não existe diferença de tipo','Aspas fazem os caracteres serem interpretados como texto.'],
['O que significa NaN?','Um resultado numérico inválido','Uma string vazia|Um booleano verdadeiro|Um comentário','NaN significa Not a Number e sinaliza um resultado numérico inválido.'],
['Qual exemplo é uma string vazia?','""','0|null|false','Uma string sem caracteres é representada por duas aspas sem conteúdo.'],
['Qual valor inicial aparece em let dado;?','undefined','null automaticamente|"undefined"|NaN obrigatoriamente','Sem inicialização, let armazena undefined.'],
['Qual é o tipo de 3.5 em JavaScript?','number','float separado de number|string|boolean','Inteiros e valores decimais comuns compartilham o tipo number.'],
['Qual exemplo é um texto que representa um número?','"18"','18|true|null','As aspas definem o valor como string.'],
['Qual função converte valores para booleano?','Boolean','Number|String|console.log','Boolean aplica as regras de conversão para true ou false.'],
['Qual é a saída?','number','string|boolean|undefined','typeof 7 retorna a string number.','console.log(typeof 7);'],
['Qual é a saída?','string','number|boolean|null','O valor está entre aspas e tem tipo string.','console.log(typeof "7");'],
['Qual é o resultado?','12','"12"|NaN|0','Number converte o texto numérico para 12.','Number("12")'],
['Qual é a saída?','23','5|6|NaN','Como ambos os operandos são strings, + concatena os textos.','console.log("2" + "3");'],
['Qual é a saída?','5','23|NaN|"23"','Após as duas conversões, + faz uma soma numérica.','console.log(Number("2") + Number("3"));'],
['Qual é o valor de Boolean(0)?','false','true|"false"|undefined','Zero é um valor falsy na conversão para booleano.'],
['Qual é o resultado de Number("abc")?','NaN','0|"abc"|true','Esse texto não representa um número válido.'],
['Qual é a saída?','boolean','string|number|object','false sem aspas é um booleano.','console.log(typeof false);'],
['Qual é o resultado de String(15)?','A string "15"','O número 15|true|NaN','String converte o número para sua representação textual.'],
['Qual é a saída?','51','6|NaN|4','Primeiro 2 + 3 resulta em 5; depois a string "1" faz + concatenar.','console.log(2 + 3 + "1");'],
['Qual é a saída?','123','6|15|NaN','A primeira string faz as adições seguintes concatenarem os operandos da esquerda para a direita.','console.log("1" + 2 + 3);'],
['Qual é a saída?','8','"102"|NaN|12','O operador - converte a string numérica para número e subtrai.','console.log("10" - 2);'],
['Qual é o resultado de Boolean("false")?','true','false|NaN|undefined','Uma string não vazia é truthy, independentemente de seu conteúdo textual.'],
['Qual é a saída?','object','null|string|undefined','Por um comportamento histórico de JavaScript, typeof null retorna object; null continua sendo um valor primitivo.','console.log(typeof null);'],
['Qual é a saída?','10','6|NaN|"55"','Os parênteses somam 2 e 3 antes de multiplicar por Number("2").','console.log(Number("2") * (2 + 3));']
],
operadores: [
['Qual operador soma dois números?','+','-|*|/','O operador + soma operandos numéricos.'],
['Qual operador subtrai números?','-','+|*|%','O operador - calcula a diferença.'],
['Qual operador multiplica números?','*','x|+|/','Em JavaScript, a multiplicação usa *.'],
['Qual operador divide números?','/','*|%|+','O operador / calcula o quociente.'],
['Qual operador retorna o resto de uma divisão?','%','/|+|**','Para esses números positivos, % fornece o resto da divisão inteira.'],
['Qual é o resultado de 4 + 3?','7','43|1|12','Somar 4 e 3 produz 7.'],
['Qual é o resultado de 9 - 4?','5','13|36|4','Subtrair 4 de 9 produz 5.'],
['Qual é o resultado de 3 * 4?','12','7|34|1','Multiplicar 3 por 4 produz 12.'],
['Qual é o resultado de 12 / 3?','4','9|36|0','12 dividido em três partes iguais dá 4.'],
['Qual é o resultado de 7 % 2?','1','3.5|0|2','7 = 2 × 3 + 1; o resto é 1.'],
['Qual recurso muda a ordem de avaliação de uma expressão?','Parênteses','Aspas apenas|Comentários apenas|Nome do arquivo','Parênteses agrupam operações que devem ser avaliadas antes.'],
['Qual operação representa o dobro de n?','n * 2','n / 2|n + 1|n % 2','Dobrar significa multiplicar por 2.'],
['Qual operador calcula uma potência em JavaScript?','**','^|//|%%','** é o operador de exponenciação; ^ tem outro significado.'],
['Qual é o resultado de 10 % 5?','0','2|5|15','10 é divisível por 5, então o resto é zero.'],
['Qual expressão calcula a metade de um número n?','n / 2','n * 2|n - 2|n % 2','Dividir por 2 calcula a metade.'],
['Qual é o resultado de 2 + 3 * 4?','14','20|24|9','A multiplicação vem antes da soma: 2 + 12.'],
['Qual é o resultado de (2 + 3) * 4?','20','14|9|24','Os parênteses fazem a soma acontecer primeiro: 5 × 4.'],
['Qual é o resultado de 2 ** 3?','8','6|5|9','2 elevado a 3 é 2 × 2 × 2.'],
['Qual é a saída?','6','2|9|12','O operador /= divide o valor atual por 2 e o armazena.','let n = 12;\nn /= 2;\nconsole.log(n);'],
['Qual é a saída?','9','6|3|18','O operador += soma 3 ao valor atual de pontos.','let pontos = 6;\npontos += 3;\nconsole.log(pontos);'],
['Qual é o resultado de 20 / 5 * 2?','8','2|10|20','Divisão e multiplicação têm a mesma precedência e são avaliadas da esquerda para a direita.'],
['Qual é o resultado de 17 % 5?','2','3|3.4|5','17 = 5 × 3 + 2.'],
['Qual é a saída?','11','10|12|1','n++ incrementa o valor em 1.','let n = 10;\nn++;\nconsole.log(n);'],
['Qual é o resultado de 8 - 3 - 2?','3','7|5|13','As subtrações são avaliadas da esquerda para a direita: 5 - 2.'],
['Qual é o resultado de 3 + 2 * (8 - 5) ** 2?','21','45|15|81','Parênteses: 3; potência: 9; multiplicação: 18; soma: 21.'],
['Qual é o valor final de total?','27','30|24|9','Primeiro 12 × 3 = 36; depois subtrai 36 × 0.25 = 9.','let total = 12 * 3;\ntotal = total - total * 0.25;'],
['Qual expressão calcula corretamente a média de a e b?','(a + b) / 2','a + b / 2|a * b / 2|a / b + 2','É preciso somar os dois valores antes de dividir a soma.'],
['Qual é a saída?','4','0|2|8','Depois de n %= 4, n vale 2. Multiplicar por 2 produz 4.','let n = 10;\nn %= 4;\nn *= 2;\nconsole.log(n);'],
['Qual é o resultado de 18 / (3 * 2) + 4?','7','16|10|5','Os parênteses produzem 6; 18 / 6 = 3; 3 + 4 = 7.'],
['Quantos pacotes completos de 4 cabem em 19 itens, usando o resto?','4','3|5|19','19 % 4 = 3. Retirando o resto, (19 - 3) / 4 = 4 pacotes.']
],
revisao: [
['Qual combinação representa um valor numérico e uma variável?','let idade = 18;','let idade = "18";|console.log("idade");|// idade 18','O literal 18 é number e fica armazenado na variável idade.'],
['Para calcular o total de itens, quais dados de entrada são úteis?','Quantidade por caixa e número de caixas','Cor do monitor e nome do navegador|Somente a mensagem de saída|Só um comentário','O total depende da quantidade em cada caixa e de quantas caixas existem.'],
['Qual instrução exibe o resultado armazenado em total?','console.log(total);','console.log("total");|let total;|// total','Sem aspas, total é lido como uma variável.'],
['O que separa entrada de processamento?','Entrada fornece dados; processamento trabalha com eles','Ambos significam apagar dados|Entrada é sempre uma imagem|Processamento é sempre digitar','O papel de cada etapa depende de como os dados são usados.'],
['Qual declaração favorece uma referência fixa de preço unitário?','const precoUnitario = 8;','const 8 = precoUnitario;|let "preço" = 8;|console precoUnitario 8;','const declara uma ligação que não será reatribuída.'],
['Qual alternativa é uma operação aritmética?','preco * quantidade','// calcular total|"preco"|let nome = "Ana";','A multiplicação é uma operação entre valores numéricos.'],
['Por que guardar um resultado em uma variável?','Para reutilizá-lo em outras instruções','Para impedir toda saída|Para sempre mudar seu tipo|Para transformar números em imagens','Um nome associado ao resultado permite referenciá-lo depois.'],
['Qual operação converte "9" em um número?','Number("9")','String(9)|Boolean("9")|console.log("9")','Number é a conversão numérica explícita.'],
['Qual valor representa uma resposta de sim ou não em lógica?','Um booleano','Uma multiplicação|Um comentário|Um identificador inválido','Valores booleanos representam dois estados: true e false.'],
['O que revisar quando um programa executa, mas calcula o total errado?','A lógica e as operações do cálculo','Só a cor do fundo|Só os comentários|Só o nome do arquivo','Executar sem erro de sintaxe não garante que o algoritmo esteja correto.'],
['Qual prática evita confundir nomes de variáveis?','Manter nomes claros e a mesma capitalização','Mudar maiúsculas aleatoriamente|Usar sempre espaços no nome|Começar todo nome com número','Identificadores são sensíveis a maiúsculas e devem ser consistentes.'],
['O que um resultado de fase deve mostrar para apoiar o aprendizado?','A resposta correta e sua explicação','Só uma letra sem contexto|Só a pontuação sem feedback|Nenhuma informação sobre erros','Explicações ajudam a entender a habilidade e a revisar erros.'],
['Qual sequência resolve um cálculo de troco?','Ler pagamento e preço, subtrair preço, exibir troco','Exibir troco antes de calculá-lo|Somar preço ao pagamento|Dividir preço pelo nome','O troco corresponde ao pagamento menos o preço.'],
['Para verificar o tipo de total, qual expressão usar?','typeof total','total++|"total"|total / 2','typeof consulta o tipo do valor atual.'],
['Qual operador usar para descobrir sobra de itens em grupos iguais?','%','+|**|=','Para quantidades inteiras positivas, % fornece a sobra da divisão.'],
['Qual é a saída?','15','10|5|50','O número 5 somado ao dobro dele resulta em 15.','let n = Number("5");\nconsole.log(n + n * 2);'],
['Qual é o resultado exibido?','Troco: 6','Troco: 34|Troco: 14|Troco: 20','O pagamento 20 menos o preço 14 resulta em 6.','const pago = 20;\nconst preco = 14;\nconsole.log("Troco: " + (pago - preco));'],
['Qual é o valor final de estoque?','9','12|3|15','A retirada diminui o estoque de 12 para 9.','let estoque = 12;\nconst vendido = 3;\nestoque -= vendido;'],
['Qual é a saída?','number','string|boolean|object','Number converte a string para um valor do tipo number.','const valor = Number("18");\nconsole.log(typeof valor);'],
['Qual expressão calcula área de um retângulo?','largura * altura','largura + altura|largura / altura|largura % altura','A área do retângulo é o produto das duas dimensões.'],
['Qual é a saída?','12','34|7|NaN','Os textos são convertidos em números antes da multiplicação.','console.log(Number("3") * Number("4"));'],
['Qual é o valor final de pontos?','140','100|40|1040','O saldo de pontos recebe 10 quatro vezes por meio do produto 10 × 4.','let pontos = 100;\npontos += 10 * 4;'],
['Qual instrução calcula um aumento de 10%?','preco = preco * 1.1;','preco = preco * 0.1;|preco = preco / 10;|preco = preco - 10;','Multiplicar por 1.1 mantém 100% e acrescenta 10% do preço.'],
['Qual é a saída?','2','0|4|12','A divisão de 14 por 4 deixa resto 2.','let itens = 14;\nconsole.log(itens % 4);'],
['Qual é o preço final da compra?','45','50|5|40','São 5 × 10 = 50; um desconto de 10% retira 5, deixando 45.','let quantidade = Number("5");\nlet total = quantidade * 10;\ntotal -= total * 0.1;\nconsole.log(total);'],
['Qual é o valor exibido?','14','7|12|10','A média é (8 + 6) / 2 = 7. O dobro da média é 14.','const a = Number("8");\nconst b = Number("6");\nlet media = (a + b) / 2;\nconsole.log(media * 2);'],
['Qual correção evita concatenação no cálculo de quantidade total?','Converter cada texto antes da soma','Converter somente a soma concatenada|Usar String nas duas entradas|Remover console.log','Number(caixa1) + Number(caixa2) calcula 12; Number(caixa1 + caixa2) daria 57.','let caixa1 = "5";\nlet caixa2 = "7";\nlet total = caixa1 + caixa2;'],
['Qual é a saída e por quê?','8, pois copia mantém o valor anterior','12, pois copia acompanha sempre base|20, pois os valores são somados|undefined, pois base mudou','Valores numéricos são copiados por valor; copia contém 4, então copia × 2 resulta em 8.','let base = 4;\nlet copia = base;\nbase = 6;\nconsole.log(copia * 2);'],
['Qual resultado é exibido?','Custo: 24','Custo: 63|Custo: 12|Custo: 18','Os valores são convertidos: (6 + 2) × 3 = 24. Depois o resultado é anexado ao texto.','const unidade = Number("6");\nconst fretePorItem = 2;\nconst quantidade = 3;\nconsole.log("Custo: " + (unidade + fretePorItem) * quantidade);'],
['Qual é a sequência final de saldo e reserva?','saldo = 70, reserva = 20','saldo = 50, reserva = 20|saldo = 70, reserva = 70|saldo = 100, reserva = 0','A reserva copia 20; saldo diminui para 80 e depois para 70. A reserva não muda.','let saldo = 100;\nconst reserva = saldo * 0.2;\nsaldo -= reserva;\nsaldo -= 10;']
]
};
const questions = Object.entries(banks).flatMap(([theme, entries]) => {
  if (entries.length !== 30) throw new Error(`${theme}: esperado 30, recebido ${entries.length}`);
  return entries.map(([enunciado, correct, distractors, explicacao, codigo], i) => ({
    id: `camp60-${theme}-${String(i+1).padStart(3,'0')}`, temas: [theme], dificuldade: i < 15 ? 'facil' : i < 24 ? 'medio' : 'dificil', tipo: 'multipla_escolha', linguagem: 'javascript', enunciado,
    ...(codigo ? { codigo } : {}), alternativas: [correct,...distractors.split('|')].map((texto,j) => ({id:'abcd'[j],texto})), corretaId: 'a', embaralharAlternativas: true,
    explicacao, dica: ({fundamentos:'Separe instruções executáveis, comentários e a intenção do programa.',algoritmos:'Acompanhe os passos na ordem e anote os valores intermediários.',entrada_saida:'Distinga o dado recebido, seu tipo e o resultado apresentado.',variaveis:'Acompanhe cada atribuição e observe let, const e a escrita dos nomes.',tipos:'Observe as aspas e faça as conversões antes de calcular.',operadores:'Resolva parênteses, potências, multiplicações e divisões antes das somas.',revisao:'Faça um teste de mesa: observe tipos, ordem e valores em cada etapa.'})[theme], ativa: true
  }));
});
await writeFile(new URL('../data/perguntas.json',import.meta.url), JSON.stringify(questions,null,2)+'\n');
console.log(`${questions.length} questões geradas.`);
